extends:
  - "spectral:oas"

functions:
  - "myCustomFunction"
functionsDir: "dist/functions"

rules:
  http-status-obsolete:
    formats: [oas3]
    severity: warn
    message: "{{property}} is an obsolete or unused HTTP status code"
    given: $.paths.*.*.responses
    then:
      field: "@key"
      function: myCustomFunction
      functionOptions:
        values: ["306", "418", "510"]

  response-must-have-500:
    description: "All responses should have a `500` response defined."
    message: "All endpoints must have a `500` response defined."
    severity: error
    formats:
      - "oas3"
    given: "$.paths[*].[get,put,post,delete,options,head,patch,trace].responses"
    then:
      - function: "defined"
        field: "500"
      - function: "pattern"
        functionOptions:
          match: "^Internal Server Error$"
        field: "500.description"
